language: rust
sudo: required

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: KdrkDaRv475Gt5fXlMQZp/YCEtmhwRu0RdbXVgUJozrYSrn1tOH5pVKLThm4uKN5e56MtCOQtkpSQDFcOKyE2wM6ca8cLxYk1eJ+bAsm9RdgMcPdE6n4i3L28ly5YSbzDyiFFYP+L/CpSzAZUMKa8cI3EU8Qi8xpQccAwmguFGCLjnH330bpYY7+lAWoi8zLhSO7K8zDxeOdT3emucWLcprmmbOYK1Kk2RMu+gR65glHpWcNPrw1DDknh12zjlpjQWlxVQCNvC8ueuZxkgeWguPbWouvtMmwT8L045Idg+8/e6w+JZXdPKduAb/UpTkZaQMws9X2wATwta7QRzFPOmq7q94dAUXJ8oFxxWd6OibIUozCILthwNzEjYcQGvAWUb5radHfOuwEKqkVPrsdjexI6ELKRhh86oW4fiQjgg99l/HPmwwbsLoEtlTWNj384DjYcUUXfSKgw95Jky6PH1Me4Yh6QvB/pjzhPIMnzayaoKX07Y/G6If+iz6vfKZoSFQ7QyYlx/h5xb8b6gG/efWjCC4NaQca8aW0U2tNhGILQB7JQ0W8Ltf/P1E7fFZgessa3L7GGVkhd9LlUhvmU8dLNK/AdIjPcy9vGAZ3A/HBPmro0OGD14gD0r2OK2uQQvL22QuVT61Xz+e9LLcdIsHg+JGBd3tHX0GCAPJzg6k=

notifications:
  email: false
