[package]
name = "options"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/options"
homepage = "https://github.com/stainless-steel/options"
documentation = "https://stainless-steel.github.io/options"
description = "It is good to know your options."
