[package]
name = "options"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/options"
homepage = "https://github.com/stainless-steel/options"
description = """
The package provides a data structure for managing named parameters.
"""
